version: '3.7'
services:
  php:
    container_name: symfony4
    ports:
      - '8070:80'
    build:
      context: .
      dockerfile: docker/build/Dockerfile

  # Configure the database
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=drupal
    ports:
      - '3307:3306'
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
